- apps/app-front/package.json
- apps/app-mobile/package.json
- apps/back-office-front/package.json
- apps/ceo-front/package.json
- apps/store-front/package.json
- apps/user-front/package.json
- apps/user-mobile/package.json
- packages/eslint-config/base.js
- packages/eslint-config/next.js
- packages/eslint-config/package.json
- packages/eslint-config/react-native.js
- packages/ui/eslint.config.mjs
- packages/ui/package.json
- yarn.lock
- nextjs 프로젝트에서 eslint가 제대로 동작하지 않는 버그 수정
- eslint warning이 있어도 스크립트에서 에러가 발생하지 않는 현상 수정
> chore: eslint 버그 수정

- apps/app-front/src/app/admin/waiting/page.tsx
[[POS] 웨이팅 요청 목록 퍼블리싱](https://www.notion.so/benkang/POS-1cd83feabad38043ba28dd1e8acd9856)
웨이팅 요청 목록 퍼블리싱 (기능 없이 레이아웃만 작업 완료 상태)
화면은 https://app-stage.fooding.im/admin/waiting 에서 확인하실 수 있습니다.
혹시 이 url에 작업하는게 아니라면 말씀 부탁드리겠습니다!
> [FE-20] 웨이팅 요청 목록 퍼블리싱

- apps/app-front/src/app/store/register/components/MemberCountStep.tsx
- apps/app-front/src/app/store/register/components/NameStep.tsx
- apps/app-front/src/app/store/register/components/TermsStep.tsx
- apps/app-front/src/app/store/register/components/WaitingStep.tsx
- apps/app-front/src/app/store/register/page.tsx
- apps/app-front/src/app/store/register/types.ts
- apps/app-front/src/app/store/waiting/page.tsx
- apps/pos-front/next-env.d.ts
[[APP] 웨이팅 - 개인정보처리방침 퍼블리싱](https://www.notion.so/benkang/APP-1cd83feabad38019bee7e5a0ac3a2111?pvs=4)
[[APP] 웨이팅 - 접수](https://www.notion.so/benkang/APP-1ca83feabad380c09183c689b1c609b5?pvs=4)
[[APP] 웨이팅 - 이름 입력](https://www.notion.so/benkang/APP-1cd83feabad380d7876df648568ecc41?pvs=4)
[[APP] 웨이팅 - 완료](https://www.notion.so/benkang/APP-1cd83feabad380c8bba2ef38adf00beb?pvs=4)
- 웨이팅 접수기능 퍼블리싱
- 웨이팅페이지에서 접수시 신청페이지로 이동
- 웨이팅 신청완료시 웨이팅페이지로 이동
> [FE-1][F-14][F-16][F-17]: 웨이팅 - 접수기능 퍼블리싱

- apps/ceo-front/src/app/devices/page.tsx
- apps/ceo-front/src/app/page.tsx
- apps/ceo-front/src/components/Home/AppBarSection.tsx
- apps/ceo-front/src/components/Home/DrawerMenuSection.tsx
- apps/ceo-front/src/components/Home/DrawerSection.tsx
- apps/ceo-front/src/components/Home/Layout.tsx
- apps/ceo-front/src/components/Home/MainContent.tsx
[[FE-23] CEO 기기 관리 퍼블리싱](https://www.notion.so/benkang/CEO-1cd83feabad380c2aaa5f35aba5544a6?pvs=4)
<br />
- CEO 전체 레이아웃 수정
- 메뉴리스트 레이아웃 수정
- devices 페이지 추가
<br />
<br />
<br />
<br />
> [FE-23] CEO 기기 관리 퍼블리싱

- apps/user-front/src/app/login/page.tsx
fix: user 소셜로그인 리다이렉트 수정
<br />
user-front에서 소셜로그인 후 메인페이지로 리다이렉트 안되는 문제 수정했습니다.
router.replace -> router.refresh() 를 이용하여 
서버 요청이 새로 발생하여 쿠키가 반영된 최신 상태로 미들웨어가 판단 리다이렉트 됩니다.
<br />
<br />
<br />
<br />
> fix: user 소셜로그인 리다이렉트 수정

- packages/design-system/.storybook/font.css
- packages/design-system/.storybook/index.css
- packages/design-system/.storybook/main.ts
- packages/design-system/.storybook/preview.tsx
- packages/design-system/eslint.config.mjs
- packages/design-system/package.json
- packages/design-system/src/components/b2c/BottomSheet.stories.tsx
- packages/design-system/src/components/b2c/Button.stories.tsx
- packages/design-system/src/components/b2c/ChipTabs.stories.tsx
- packages/design-system/src/components/b2c/Dialog.stories.tsx
- packages/design-system/src/components/b2c/Tabs.stories.tsx
- packages/design-system/src/components/b2c/Tag.stories.tsx
- packages/design-system/vite.config.ts
- yarn.lock
<br />
컴포넌트 사용 방법 확인할수 있도록 스토리북을 사용해 문서화
스토리북 스크립트
```
cd packages/design-system
yarn storybook
```
<br />
<br />
<br />
<br />
> chore: design system 스토리북 추가

- apps/app-front/src/app/store/select/page.tsx
- packages/api/src/app/store/index.ts
- packages/api/src/app/store/type.ts
<br />
<br />
<br />
<br />
<br />
> fix: [APP] 가게 리스트 조회 API 응답 스키마 페이징 → 리스트 구조로 수정

- apps/user-front/src/app/notifications/page.tsx
- packages/design-system/src/components/b2c/ErrorFallback.stories.tsx
- packages/design-system/src/components/b2c/ErrorFallback.tsx
- packages/design-system/src/components/b2c/index.ts
<br />
<br />
<br />
<br />
<br />
> ErrorFallback 컴포넌트 추가

- apps/user-front/src/tabs/home/Home.tsx
- packages/design-system/src/components/b2c/Skeleton.stories.tsx
- packages/design-system/src/components/b2c/Skeleton.tsx
- packages/design-system/src/components/b2c/index.ts
<br />
- Skeleton 컴포넌트 추가
- Home 로딩, 에러 UI 추가
<br />
<br />
<br />
<br />
> chore: Skeleton 컴포넌트 추가

- apps/user-front/src/app/ping.ts
> revert: ping

- .dockerignore
- .github/workflows/design-system-develop.yaml
- .github/workflows/design-system-main.yaml
- packages/design-system/Dockerfile
- packages/design-system/nginx.conf
스토리북을 구성합니다.
https://ds.fooding.im
https://ds-stage.fooding.im
> INFRA-14: 스토리북 구성1

- packages/api/src/user/stores/mock.ts
<br />
<br />
<br />
<br />
<br />
> chore: 타입에러 수정

- apps/user-front/src/tabs/my-page/MyPage.tsx
<br />
마이페이지에서 스크롤이 되지 않는 버그 수정
<br />
<br />
<br />
<br />
> fix: 마이페이지 스크롤 안되는 버그 수정

- apps/user-front/src/mocks/handlers.ts
<br />
GET /user/stores api 모킹 추가
<br />
<br />
<br />
<br />
> [user-front] chore: mock 추가

- apps/user-front/src/components/Store/StoresList.tsx
- apps/user-front/src/screens/bookmarks/Bookmarks.tsx
- apps/user-front/src/screens/notifications/components/NotificationList.tsx
- apps/user-front/src/screens/store-detail/StoreDetail.tsx
- apps/user-front/src/screens/store-detail/components/tabs/Home.tsx
- apps/user-front/src/screens/store-detail/components/tabs/ReviewDetail.tsx
- packages/design-system/src/components/b2c/EmptyState.stories.tsx
- packages/design-system/src/components/b2c/EmptyState.tsx
- packages/design-system/src/styles/shared.css
<br />
- EmptyState 컴포넌트 스타일 수정
- 빈 목록 문구 전반적으로 수정
- gray 관련 컬러 토큰 피그마 값과 다른 부분 수정
<br />
<br />
<br />
<br />
> chore: EmptyState 스타일 수정

- apps/app-front/src/app/store/waiting/components/PhoneStep.tsx
- apps/app-front/src/app/store/waiting/components/registerWating.tsx
- apps/app-front/src/components/Login/LoginForm.tsx
- apps/app-front/src/components/TermsAgreement.tsx
- packages/design-system/package.json
- packages/design-system/src/components/b2b/Button.stories.tsx
- packages/design-system/src/components/b2b/Checkbox.stories.tsx
- packages/design-system/src/components/b2b/Checkbox.tsx
- packages/design-system/src/components/b2b/Input.stories.tsx
- packages/design-system/src/components/b2b/Input.tsx
- packages/design-system/src/components/b2b/index.ts
[[B2B] 디자인시스템 - 스토리북에반영 (Checkbox, Input)](https://www.notion.so/benkang/1ca83feabad380859559d59a6f323790?v=1ca83feabad3800fac18000cac82606b&p=22283feabad380ef8332feccf5e6133a&pm=s)
<br />
- 디자인 시스템 컴포넌트 Checkbox, Input 추가
- 오타 수정, 사용하지 않는 import 제거
<br />
<br />
<br />
<br />
> [FE-146] [B2B] 디자인 시스템 Checkbox, Input 스토리북에 반영

- apps/user-front/src/screens/store-detail/StoreDetail.tsx
- apps/user-front/src/tabs/home/components/CategoryTabs.tsx
- packages/design-system/src/components/b2c/Checkbox.stories.tsx
- packages/design-system/src/components/b2c/Checkbox.tsx
- packages/design-system/src/components/b2c/ChipButton.stories.tsx
- packages/design-system/src/components/b2c/ChipButton.tsx
- packages/design-system/src/components/b2c/ChipFilter.stories.tsx
- packages/design-system/src/components/b2c/ChipFilter.tsx
- packages/design-system/src/components/b2c/ChipTabs.stories.tsx
- packages/design-system/src/components/b2c/ChipTabs.tsx
- packages/design-system/src/components/b2c/Tabs.stories.tsx
- packages/design-system/src/components/b2c/Tabs.tsx
- packages/design-system/src/components/b2c/index.ts
<br />
컴포넌트 사용법은 스토리북 참고해주세요!
- Checkbox 컴포넌트 추가 (체크된 상태의 UI는 피그마 업데이트 이후 수정 예정)
- ChipFilter 컴포넌트 추가
- ChipButton 컴포넌트 추가
- ChipTabs, Tabs 컴포넌트에 scrollable prop 추가
```tsx
// 기존: 마이너스 마진, 오버플로우 등 스타일을 직접 추가해야 했음
<ChipTabs defaultValue='home' className='-mx-grid-margin w-auto'>
<ChipTabs.List className='overflow-x-auto w-full scrollbar-hide px-grid-margin'>
<ChipTabs.Trigger value='home'>홈</ChipTabs.Trigger>
<ChipTabs.Trigger value='news'>소식</ChipTabs.Trigger>
<ChipTabs.Trigger value='menu'>메뉴</ChipTabs.Trigger>
<ChipTabs.Trigger value='photo'>사진</ChipTabs.Trigger>
<ChipTabs.Trigger value='review'>리뷰</ChipTabs.Trigger>
<ChipTabs.Trigger value='info'>매장정보</ChipTabs.Trigger>
</ChipTabs.List>
</ChipTabs>
// 변경 후: scrollable prop을 전달하면 가로 스크롤 가능
<ChipTabs defaultValue='home' scrollable> …
```
> chore: [b2c] Checkbox, ChipFilter, ChipButton 추가 

- apps/user-front/src/components/Store/ReviewDetailCard.tsx
- apps/user-front/src/components/Store/StarRating.tsx
- apps/user-front/src/screens/store-detail/components/tabs/ReviewDetail.tsx
- apps/user-front/src/tabs/reservation/Reservation.tsx
- apps/user-front/src/tabs/reservation/components/ReservationCanceledCard.tsx
- apps/user-front/src/tabs/reservation/components/ReservationCanceledList.tsx
- apps/user-front/src/tabs/reservation/components/ReservationCard.tsx
- apps/user-front/src/tabs/reservation/components/ReservationCompletedCard.tsx
- apps/user-front/src/tabs/reservation/components/ReservationCompletedList.tsx
- apps/user-front/src/tabs/reservation/components/ReservationScheuledList.tsx
- apps/user-front/src/utils/date.ts
- apps/user-front/src/utils/rating.ts
- packages/api/src/configs/queryKeys.ts
- packages/api/src/user/index.ts
- packages/api/src/user/reservations/index.ts
- packages/api/src/user/reservations/mock.ts
- packages/api/src/user/reservations/type.ts
[[FE-150] USER 예약/웨이팅 리스트 구현
](https://www.notion.so/benkang/USER-22483feabad380cda852d85ff53a09c8?source=copy_link)<br />
- 예약/웨이팅 퍼블리싱 작업 완료했습니다.
- 현재 데이터는 목데이터로 추후 API 나오면 타입 수정 하겠습니다.
<br />
<br />
<br />
<br />
> [FE-150] USER 예약/웨이팅 리스트 구현

- apps/app-front/src/app/store/reward/use/components/Coupon.tsx
- apps/app-front/src/app/store/reward/use/components/CouponList.tsx
<br />
- Coupon 컴포넌트 min-width 적용
- CouponList의 grid 관련 스타일 코드를 반응형으로 수정하여 화면 크기에 따라 열 수가 조절되도록 개선
<br />
<br />
<br />
<br />
> [chore] APP 쿠폰 리스트 컴포넌트 반응형 그리드 적용

- packages/design-system/src/components/b2c/BottomSheet.stories.tsx
- packages/design-system/src/components/b2c/BottomSheet.tsx
- packages/design-system/src/components/b2c/Select.stories.tsx
- packages/design-system/src/components/b2c/Select.tsx
- packages/design-system/src/components/b2c/TextField.stories.tsx
- packages/design-system/src/components/b2c/TextField.tsx
<br />
- BottomSheet 컴포넌트에 Select 기능 추가
- Select 컴포넌트 추가
- TextField 컴포넌트 추가
자세한 사용법은 스토리북 참고해주세요!
<br />
<br />
<br />
<br />
> [user-front] chore: BottomSheetSelect, Select, TextField 추가

- apps/user-front/src/components/Carousel.tsx
- apps/user-front/src/components/ImageGallery.tsx
- apps/user-front/src/screens/store-detail/StoreDetail.tsx
- apps/user-front/src/tabs/home/components/Banner.tsx
- packages/design-system/src/components/b2c/FullscreenBottomSheet.tsx
<br />
- ImageGallery 컴포넌트 추가
- FullscreenBottomSheet 컴포넌트에 hideCloseButton 옵션 추가
- Carousel 컴포넌트에 Carousel.Region 추가
<br />
<br />
<br />
<br />
> [user-front] chore: ImageGallery 컴포넌트 추가

- apps/ceo-front/src/app/login/components/LoginForm.tsx
- apps/ceo-front/src/app/login/components/RegisterForm.tsx
- apps/ceo-front/src/app/login/page.tsx
- apps/ceo-front/src/app/store/select/page.tsx
- apps/ceo-front/src/components/Layouts/MainLayout.tsx
- apps/ceo-front/src/hooks/useLoginForm.ts
- packages/api/src/auth/index.ts
- packages/api/src/auth/type.ts
- packages/design-system/src/styles/b2c.css
[CEO 회원가입](https://www.notion.so/benkang/1ca83feabad380859559d59a6f323790?v=1ca83feabad3800fac18000cac82606b&p=23683feabad380b5b2e7f47555a5adb0&pm=s)
<br />
- 회원가입 폼 UI 구현
- 회원가입 API 연동
메인 매장선택 페이지(/store/select)는 임시로 생성해뒀고, 다음 PR에서 UI 수정/API 연동 진행하겠습니다~
<br />
<br />
<br />
<br />
> [FE-167] CEO 회원가입 구현

- packages/design-system/src/components/ceo/DatePicker.stories.tsx
- packages/design-system/src/components/ceo/DatePicker.tsx
- packages/design-system/src/components/ceo/RadioButton.stories.tsx
- packages/design-system/src/components/ceo/RadioButton.tsx
- packages/design-system/src/components/ceo/RadioButtonGroup.stories.tsx
- packages/design-system/src/components/ceo/RadioButtonGroup.tsx
- packages/design-system/src/components/ceo/RecurringDatePicker.stories.tsx
- packages/design-system/src/components/ceo/RecurringDatePicker.tsx
- packages/design-system/src/components/ceo/index.ts
- packages/design-system/src/styles/shared.css
[[FE-174] CEO 스토리북 데이트피커
](https://www.notion.so/benkang/CEO-23d83feabad38025a5a9dc23fa3683a3?v=1ca83feabad3800fac18000cac82606b&source=copy_link)<br />
- 데이트 피커 컴포넌트와 스타일 적용한 라디오 버튼, 라디오버튼 그룹 storybook에 적용했습니다.
- 디자이너 분과 소통해서 오늘 날짜는 보더로 표시하기로 했습니다.
<br />
<br />
<br />
<br />
> [FE-174] CEO 스토리북 데이트피커

- apps/back-office-front/src/app/leads/[id]/page.tsx
- apps/back-office-front/src/app/leads/page.tsx
- apps/back-office-front/src/app/regions/[id]/page.tsx
- apps/back-office-front/src/app/regions/page.tsx
- apps/back-office-front/src/app/reviews/CreateReviewDialog.tsx
- apps/back-office-front/src/app/reviews/EditReviewDialog.tsx
- apps/back-office-front/src/app/reviews/ReviewList.tsx
- apps/back-office-front/src/app/reviews/page.tsx
- apps/back-office-front/src/app/rewards/logs/page.tsx
- apps/back-office-front/src/app/rewards/page.tsx
- apps/back-office-front/src/app/rewards/points/page.tsx
- apps/back-office-front/src/app/stores/[id]/CreateStoreServiceDialog.tsx
- apps/back-office-front/src/app/stores/[id]/StoreServiceManagement.tsx
- apps/back-office-front/src/app/stores/[id]/page.tsx
- apps/back-office-front/src/components/Layout/AdminLayout.tsx
- packages/api/src/admin/index.ts
- packages/api/src/admin/leads/index.ts
- packages/api/src/admin/leads/type.ts
- packages/api/src/admin/menus/index.ts
- packages/api/src/admin/menus/type.ts
- packages/api/src/admin/regions/index.ts
- packages/api/src/admin/regions/type.ts
- packages/api/src/admin/reviews/index.ts
- packages/api/src/admin/reviews/type.ts
- packages/api/src/admin/store-services/index.ts
- packages/api/src/admin/store-services/type.ts
- packages/api/src/admin/stores/type.ts
- packages/api/src/shared.ts
<br />
<br />
- [v] 기능 추가
<br />
<br />
<br />
> 리뷰 목록,  스토어 서비스 1차 추가

- apps/ceo-front/src/app/layout.tsx
- apps/ceo-front/src/app/page.tsx
<br />
<br />
<br />
<br />
<br />
> fix: lint erros

- apps/user-front/src/components/Layout/Header.tsx
<br />
- 개발용으로 헤더에 설정한 border가 남아있는 버그 수정
<br />
<br />
<br />
<br />
> fix:  헤더 UI 버그 수정

- packages/design-system/src/components/ceo/Tag.stories.tsx
- packages/design-system/src/components/ceo/Tag.tsx
- packages/design-system/src/components/ceo/index.ts
- packages/design-system/src/styles/shared.css
<br />
- Tag 컴포넌트 추가
- fooding-blue 값 수정
컴포넌트 사용 방법은 스토리북 참고해주세요!
<br />
<br />
<br />
<br />
> [CEO] Tag 컴포넌트 추가

- apps/user-front/package.json
- apps/user-front/src/libs/webview-bridge/index.ts
- apps/user-front/src/libs/webview-bridge/temp.ts
- yarn.lock
<br />
<br />
- [v ] 기능 추가
<br />
<br />
<br />
> chore: temp

- packages/design-system/src/components/ceo/IconButton.stories.tsx
- packages/design-system/src/components/ceo/IconButton.tsx
<br />
- 높이 38px, 텍스트 방향 패딩 16px로 조정
- 호버 스타일 수정
<br />
<br />
<br />
<br />
> [CEO] IconButton 스타일 수정

- packages/design-system/src/styles/b2c.css
<br />
- 티이포그래피 변수 선언을 tailwindcss 인텔리센스가 인식할 수 있는 형태로 수정
<br />
<br />
<br />
<br />
> chore: 타이포그래피 인텔리센스 개선
